INSERT INTO products (
    code,
    title,
    description,
    price_amount,
    price_currency,
    product_type,
    is_active,
    is_visible,
    sort_order,
    is_featured,
    inventory_mode,
    inventory_count,
    purchase_limit_per_user,
    requires_admin_delivery,
    success_message_template,
    created_at,
    updated_at
)
VALUES (
    'FRIENDS_SUPPORT_ACCESS',
    'SLH Friends Access',
    'Entry access to the SLH friends/support group.',
    22.2221,
    'ILS',
    'GROUP_ACCESS',
    TRUE,
    TRUE,
    10,
    TRUE,
    'unlimited',
    NULL,
    1,
    TRUE,
    'לאחר אישור התשלום תקבל קישור הצטרפות לקבוצת החברים.',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
)
ON CONFLICT (code) DO UPDATE
SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    price_amount = EXCLUDED.price_amount,
    price_currency = EXCLUDED.price_currency,
    product_type = EXCLUDED.product_type,
    is_active = EXCLUDED.is_active,
    is_visible = EXCLUDED.is_visible,
    sort_order = EXCLUDED.sort_order,
    is_featured = EXCLUDED.is_featured,
    inventory_mode = EXCLUDED.inventory_mode,
    inventory_count = EXCLUDED.inventory_count,
    purchase_limit_per_user = EXCLUDED.purchase_limit_per_user,
    requires_admin_delivery = EXCLUDED.requires_admin_delivery,
    success_message_template = EXCLUDED.success_message_template,
    updated_at = CURRENT_TIMESTAMP;