FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    fastapi==0.115.0 \
    uvicorn==0.30.1 \
    python-telegram-bot==21.4 \
    sqlalchemy==2.0.36 \
    psycopg2-binary \
    alembic \
    python-dotenv \
    pydantic \
    httpx

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
