import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
WEBHOOK_BASE = os.getenv("WEBHOOK_BASE")
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET", "webhook-123")
ADMIN_CHAT_ID = int(os.getenv("ADMIN_CHAT_ID", "0"))
GROUP_MONITOR_ID = int(os.getenv("GROUP_MONITOR_ID", "-1001748319682"))
GROUP_PREMIUM_INVITE_LINK = os.getenv("GROUP_PREMIUM_INVITE_LINK", "https://t.me/+e8GeOmh0CD82ZmI0")

PRICE_TEXT = "2 TON"
BANK_DETAILS = ""
ALT_TELEGRAM_ROUTE = "UQCr743gEr_nqV_0SBkSp3CtYS_15R3LDLBvLmKeEv7XdGvp"
ASSETS_PROMO_IMAGE_PATH = "assets/promo_image.jpg"
